// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQjXpBbn1kh4Uq_NAsZxWvkMEus9nSIBM',
    appId: '1:41729518235:web:dfcdcf0dcfdf9915c2343e',
    messagingSenderId: '41729518235',
    projectId: 'water-quality-monitoring-94502',
    authDomain: 'water-quality-monitoring-94502.firebaseapp.com',
    storageBucket: 'water-quality-monitoring-94502.firebasestorage.app',
    measurementId: 'G-NXDDST09NS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHS3iTA3Ut913PVBS4DNBrP-mVKwCjdP8',
    appId: '1:41729518235:android:f54da50bc69dd860c2343e',
    messagingSenderId: '41729518235',
    projectId: 'water-quality-monitoring-94502',
    storageBucket: 'water-quality-monitoring-94502.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmLzSGZJxBZaZjPj0No7dbSB5DxStiG84',
    appId: '1:41729518235:ios:dbda906272326937c2343e',
    messagingSenderId: '41729518235',
    projectId: 'water-quality-monitoring-94502',
    storageBucket: 'water-quality-monitoring-94502.firebasestorage.app',
    iosBundleId: 'com.example.waterQualityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmLzSGZJxBZaZjPj0No7dbSB5DxStiG84',
    appId: '1:41729518235:ios:dbda906272326937c2343e',
    messagingSenderId: '41729518235',
    projectId: 'water-quality-monitoring-94502',
    storageBucket: 'water-quality-monitoring-94502.firebasestorage.app',
    iosBundleId: 'com.example.waterQualityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQjXpBbn1kh4Uq_NAsZxWvkMEus9nSIBM',
    appId: '1:41729518235:web:e128775dbc3c60a9c2343e',
    messagingSenderId: '41729518235',
    projectId: 'water-quality-monitoring-94502',
    authDomain: 'water-quality-monitoring-94502.firebaseapp.com',
    storageBucket: 'water-quality-monitoring-94502.firebasestorage.app',
    measurementId: 'G-5RX9RLZ722',
  );
}
